### ISSUE TITLE
Array-Issue2

### ISSUE THREAD

**Issue by Bhawna11agg** [Bhawna11agg/Uplift-Project#16]
Question Link:: "https://www.interviewbit.com/problems/wave-array/"

The question was asked in Google, Adobe, Amazon.

**Comment by radadiyamohit81** [comment]
can i solve this question

**Comment by rakshithnv** [comment]
//check this 
#include<iostream>
#include<algorithm>
using namespace std;

// A utility method to swap two numbers.
void swap(int *x, int *y)
{
    int temp = *x;
    *x = *y;
    *y = temp;
}

// This function sorts arr[0..n-1] in wave form, i.e.,
// arr[0] >= arr[1] <= arr[2] >= arr[3] <= arr[4] >= arr[5]..
void sortInWave(int arr[], int n)
{
    // Sort the input array
    sort(arr, arr+n);

    // Swap adjacent elements
    for (int i=0; i<n-1; i += 2)
        swap(&arr[i], &arr[i+1]);
}

// Driver program to test above function
int main()
{
    int arr[] = {1,2,3,4};
    int n = sizeof(arr)/sizeof(arr[0]);
    sortInWave(arr, n);
    for (int i=0; i<n; i++)
       cout << arr[i] << " ";
    return 0;
}

**Comment by radadiyamohit81** [comment]
can i directly upload code into the issues folder?

**Comment by Bhawna11agg** [comment]
Rakshith!! from next time don't send code here, first of all, ask in comment to assign the issue and if it is assigned to you then make a pull request of code. And don't take a sample input your code must work on every input

**Comment by Bhawna11agg** [comment]
Mohit!! you have to upload your code in the same manner as your first issue code is there I have made some changes in your first pull request of issue keep in it mind

**Comment by radadiyamohit81** [comment]
ok sure

**Comment by Bhawna11agg** [comment]
Issue Solved
