### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by deepika-rana** [Bhawna11agg/Uplift-Project#182]
An expression containing open and close parentheses, No other operator or character will be there in expression. We need to remove minimum number of parentheses to make the input string valid. If more than one valid output print one among them.

Ex: Input  : str = “()())()” 
Output : ()()() (())()
There are two possible solutions
"()()()" and "(())()"
Print any one of them.

**Comment by radadiyamohit81** [comment]
can i solve this issue
