### ISSUE TITLE
Guessing Game

### ISSUE THREAD

**Issue by deepika-rana** [Bhawna11agg/Uplift-Project#213]
**Statement:**

The computer proposes a number in range 1-1500 and the user should guess it.
At every step of the game, the user tells the computer his assumption about a number and the computer tells if the user guessed it right. Otherwise, the computer tells the player if his/her number is less or more than the proposed number and the user tries again.

**Deadline: 25/07/2020 11:59 p.m.**

**Edit - Submit the project issue as Project/GuessingGame.cpp**

**Comment by Bhawna11agg** [comment]
those who want to do this must:
1. Submit all his assignments.
2. Code in c++
3. comment that you want to take issue if it is assigned to you then only work on it.
4. only 6 students will work on issue so if already 6 are working then don't comment.

**Comment by Bhawna11agg** [comment]
Best of all 6 will be merged

**Comment by radadiyamohit81** [comment]
can I solve this issue? if yes please assign it to me

**Comment by Bhawna11agg** [comment]
Have you completed your graph assignment?

**Comment by radadiyamohit81** [comment]
Yes It's Done

**Comment by radadiyamohit81** [comment]
Ya it's done but I did 4 question

**Comment by Bhawna11agg** [comment]
Start working in it @radadiyamohit81

**Comment by radadiyamohit81** [comment]
done ma'am check my PR

**Comment by manviguptag** [comment]
I want to do this issue but have not completed the assignments. Can I please work on this?

**Comment by Bhawna11agg** [comment]
Sorry Manvi, But you have not just done a single assignment completely.So you cant

**Comment by manviguptag** [comment]
What if I completed 1 assignment till morning.

**Comment by Bhawna11agg** [comment]
not assignment1, if you can do week4 assignment till tomorrow then submit the PR of issue

**Comment by Bhawna11agg** [comment]
Try to di it as much as you can

**Comment by manviguptag** [comment]
I will try. Thank you.
