### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by deepika-rana** [Bhawna11agg/Uplift-Project#231]
The game is to be played between two user and computer. One of the player chooses ‘O’ and the other ‘X’ to mark their respective cells. The user gets a chance to select 'X' or 'O'. 
The game starts with one of the players and the game ends when one of the players has one whole row/ column/ diagonal filled with his/her respective character.
If no one wins, then the game is said to be draw.

**Deadline : 30/07/2020 11:59 p.m.**

_Use the path as Projects/Name of the Game.cpp_

**Comment by radadiyamohit81** [comment]
can i do this issue?
