### ISSUE TITLE
Bhawna and Dice problem

### ISSUE THREAD

**Issue by Bhawna11agg** [Bhawna11agg/Uplift-Project#239]
Bhawna has d dice and each die has f faces numbered 1, 2, ..., f.
she decided to play a game with her friend Garima. Garima challenged that the number of possible ways (out of f*d total ways)  to roll the dice so the sum of the face-up numbers equals the target sum is always greater than the Integer range but Bhawna said it will always be in Integer range. So they decided it by calling Kashani. Kashani finds some difficulty to tell so you have to tell who is correct and print the number of possible ways.
Sample test case:
Input: d = 1, f = 6, target = 3
Output: Bhawna:: 1

Input: d = 30, f = 30, target = 500
Output: Garima (no need to print number of possible ways)

**Comment by deepika-rana** [comment]
Are we going to put this game as well in the project along with earlier 5?

**Comment by Bhawna11agg** [comment]
Sorry, this is just for practice
