### ISSUE TITLE
Array-Issue1

### ISSUE THREAD

**Issue by Bhawna11agg** [Bhawna11agg/Uplift-Project#9]
Solve this question of the array that comes in Amazon.
Link:: "https://www.interviewbit.com/problems/first-missing-integer/"

Let's see who can solve it...The one who will able to solve
The one who comment it first will get the issue and he has to solve it in an hour otherwise questions will be passed to other students.
Let's give it a try.
All the best:)

**Comment by radadiyamohit81** [comment]
int Solution::firstMissingPositive(vector<int> &A) {
    int i=0,j=0;
    for(i=0;i<A.size();i++)
    {
        if(A[i]<=0)
        {
            int temp=A[i];
            A[i]=A[j];
            A[j]=temp;
            j++;
        }
    }
    A.erase (A.begin(),A.begin()+j);
    int i;
    for(i=0;i<A.size();i++)
    {
        if(abs(A[i])-1<A.size() && A[abs(A[i])-1]>0)
            A[abs(A[i])-1]=-A[abs(A[i])-1];
    }
    for(i=0;i<A.size();i++)
    {
        if(A[i]>0)
            return i+1;
    }
    return A.size()+1;
}

**Comment by Bhawna11agg** [comment]
Hey!! First of all if you want to do any issue the comment on it that you can solve it so assign it to me and then if issue is assigned to you then first of all run that code in compile if it is showing correct answer after submit then give you code here...it is showing compilation error as you have not tell the template to vector and declare I two times and all

**Comment by radadiyamohit81** [comment]
//come up with better solution
int Solution::firstMissingPositive(vector<int> &A)
{
    sort(A.begin(), A.end());
    int c = 1;
    for (auto const& a : A)
    {
        if (a<1)
            continue;
        else if (a==c)
        {
            ++c;
            continue;
        }
        else
            break;
    }
    return c;
}

**Comment by radadiyamohit81** [comment]
i can solve this question so assign it to me...

**Comment by Bhawna11agg** [comment]
Yes, go with it Mohit

**Comment by radadiyamohit81** [comment]
int Solution::firstMissingPositive(vector<int> &A) {
    sort(A.begin(), A.end());
    int c = 1;
    for (auto const& i : A)
    {
        if (i<1)
            continue;
        else if (i==c)
        {
            ++c;
            continue;
        }
        else
            break;
    }
    return c;
}

**Comment by Bhawna11agg** [comment]
Code is perfect so just make a pull request and name the file same as the issue name..Well done

**Comment by Bhawna11agg** [comment]
Solved.
