### ISSUE TITLE
Find middle element of linked list without traversing whole list (partial traversing is allowed)

### ISSUE THREAD

**Issue by deepika-rana** [Bhawna11agg/Uplift-Project#98]
**Hint:** Use two pointers. Move one pointer by one and another pointer by two. When the fast pointer reaches end slow pointer will reach the middle of the linked list.

**Comment by Pratiksha-19** [comment]
/*Function to find Midpoint of Linked List*/
[Midpoint of LL.txt](https://github.com/Bhawna11agg/Uplift-Project/files/4831401/Midpoint.of.LL.txt)

**Comment by deepika-rana** [comment]
The soultion is correct Pratiksha so now save the file with extension of language and save it under issues

**Comment by Pratiksha-19** [comment]
Alright ma'am.
